<a href="https://colab.research.google.com/github/bkvkrll/PyTorch/blob/main/lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch
import torchvision

In [19]:
import numpy as np
from torch.autograd import Variable

In [5]:
# 1. Создайте случайный FloatTensor размера 3x4x5
tensor = torch.rand(3, 4, 5).type(torch.float32)

print(tensor)

tensor([[[0.3422, 0.8009, 0.9574, 0.7692, 0.7511],
         [0.4403, 0.2422, 0.9884, 0.5316, 0.0490],
         [0.3483, 0.7228, 0.9801, 0.7470, 0.0098],
         [0.2926, 0.4745, 0.4889, 0.8747, 0.4645]],

        [[0.2484, 0.4731, 0.0312, 0.3052, 0.3419],
         [0.7544, 0.6170, 0.4457, 0.6215, 0.0540],
         [0.8626, 0.4608, 0.6446, 0.3839, 0.2975],
         [0.1289, 0.1002, 0.1687, 0.0596, 0.6504]],

        [[0.6194, 0.3633, 0.6569, 0.8951, 0.8443],
         [0.4346, 0.7948, 0.2958, 0.5252, 0.2849],
         [0.6624, 0.7189, 0.7872, 0.5648, 0.1520],
         [0.0476, 0.2421, 0.7556, 0.5008, 0.0342]]])


In [6]:
# 2. Выведите его форму (shape)
tensor.shape

torch.Size([3, 4, 5])

In [12]:
# 3. Приведите его к форме 6х10
tensor = tensor.reshape(6,10)
tensor

tensor([[0.3422, 0.8009, 0.9574, 0.7692, 0.7511, 0.4403, 0.2422, 0.9884, 0.5316,
         0.0490],
        [0.3483, 0.7228, 0.9801, 0.7470, 0.0098, 0.2926, 0.4745, 0.4889, 0.8747,
         0.4645],
        [0.2484, 0.4731, 0.0312, 0.3052, 0.3419, 0.7544, 0.6170, 0.4457, 0.6215,
         0.0540],
        [0.8626, 0.4608, 0.6446, 0.3839, 0.2975, 0.1289, 0.1002, 0.1687, 0.0596,
         0.6504],
        [0.6194, 0.3633, 0.6569, 0.8951, 0.8443, 0.4346, 0.7948, 0.2958, 0.5252,
         0.2849],
        [0.6624, 0.7189, 0.7872, 0.5648, 0.1520, 0.0476, 0.2421, 0.7556, 0.5008,
         0.0342]])

In [13]:
# 4. Создайте случайный IntTensor размера 10
tensor_1 =torch.IntTensor(10)
print(tensor_1)

tensor([104707776,         0,  16843009,  16843009,  16843009,  16843009,
         16843009,  16843009,  16843009,  16843009], dtype=torch.int32)


In [15]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a = tensor * tensor_1
a


tensor([[35830936.0000,        0.0000, 16126125.0000, 12954927.0000,
         12650075.0000,  7416333.5000,  4079822.5000, 16647055.0000,
          8953736.0000,   824775.7500],
        [36467980.0000,        0.0000, 16507511.0000, 12581649.0000,
           165511.5156,  4927958.5000,  7991618.0000,  8234171.0000,
         14732463.0000,  7824250.0000],
        [26006456.0000,        0.0000,   525589.0625,  5140466.5000,
          5759402.5000, 12706384.0000, 10392936.0000,  7506984.5000,
         10467656.0000,   910105.0625],
        [90322472.0000,        0.0000, 10857808.0000,  6466170.0000,
          5010884.5000,  2171339.7500,  1687947.5000,  2840724.5000,
          1003366.3125, 10955214.0000],
        [64857552.0000,        0.0000, 11063460.0000, 15075420.0000,
         14220374.0000,  7320775.5000, 13386436.0000,  4983001.5000,
          8845634.0000,  4798207.5000],
        [69356600.0000,        0.0000, 13258244.0000,  9513092.0000,
          2560316.0000,   801765.8750,  4

In [17]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
b = a @ a.T
b

tensor([[2.3014e+15, 2.0826e+15, 1.4358e+15, 3.6469e+15, 3.1525e+15, 3.1650e+15],
        [2.0826e+15, 2.1950e+15, 1.3915e+15, 3.7034e+15, 3.0918e+15, 3.1384e+15],
        [1.4358e+15, 1.3915e+15, 1.1724e+15, 2.5037e+15, 2.2184e+15, 2.1113e+15],
        [3.6469e+15, 3.7034e+15, 2.5037e+15, 8.4796e+15, 6.2610e+15, 6.5423e+15],
        [3.1525e+15, 3.0918e+15, 2.2184e+15, 6.2610e+15, 5.1173e+15, 5.0260e+15],
        [3.1650e+15, 3.1384e+15, 2.1113e+15, 6.5423e+15, 5.0260e+15, 5.3339e+15]])

In [20]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
y = x**3 + x - 75*x
y.backward(x)
print(x.grad)

tensor([ -71.0000,  -36.6250, -124.0000])


In [23]:
# 8. Создайте единичный тензор размера 5x6
ones_tensor = torch.ones((5, 6))

print(ones_tensor)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [25]:
# 9. Переведите его в формат numpy
print(ones_tensor.numpy())

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
